name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    env:
      DOCKERHUB_REPOSITORY: bernda/yocto-dockerfiles
      REPO: bernda/yocto-dockerfiles
      DISTRO_TO_BUILD: ubuntu-18.04

    runs-on: ubuntu-18.04
    
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Build image
        if: success()
        run: |
          ./build_container.sh

      - name: Login to docker hub        
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to docker registry
        if: success()
        uses: actions-hub/docker@master
        with:
          name: ${DOCKERHUB_REPOSITORY}
          args: push ${DOCKERHUB_REPOSITORY}:ubuntu-18.04-base
